
### Uncomment to configure additional attributes of Application
# application:
#   timezone: Europe/Berlin  #default
#   admin_email: string
#   admin_password: string

# application_table:
questions:
  phase-1:
    phaseLabel: "Test Phase 1"
    startDate: 2023-12-01  # format: %Y-%m-%d
    endDate: 2024-12-10  # format: %Y-%m-%d
    sections:
      - name: Allgemein
        description: Wir benÃ¶tigen diese Informationen um ABC auszuwerten
      - name: Euer Team
        description: Hier fragen wir Informationen zu euerer Teamstruktur ab
    questions:
      - questionType: shortText
        order: 1
        question: What's your name?
        mandatory: true
        maxTextLength: 20
        formattingRegex: PHONE_NUMBER  # optional; Other predefined values: "EMAIL", "NUMBERS", "LETTERS", any JS Regex
        #formattingDescription: Telefonnummer # if formattinRegex not set or Predefined Value => ignored; else => mandatory
        note: e.g. Max Mustermann
        preInformationBox: We need your Email Address so we can contact you! # optional
        postInformationBox: We won't pass this data to a 3rd party! # optional
        sectionNumber: 1
      - questionType: longText
        order: 2
        question: What's your name and birthday?
        mandatory: true
        maxTextLength: 200
        note: "hint: please use dd/mm/yyyy for your birthday"
        sectionNumber: 1
      - questionType: multipleChoice
        order: 4
        question: What's your name and birthday?
        minAnswers: 0
        maxAnswers: 2
        Answers:
          - Possible Answer 1
          - Possible Answer 2
          - Possible Answer 3
        mandatory: false
        userInput: true
        sectionNumber: 1
      - questionType: videoUpload
        order: 3
        question: Please Upload this Video
        mandatory: false
        maxFileSizeInMB: 2.0  # in Mega Byte
        sectionNumber: 1
      - questionType: datePicker
        order: 5
        question: When do you have birthday?
        minDate: 1993-06-21  # format: %Y-%m-%d
        maxDate: 2023-06-21  # format: %Y-%m-%d
        mandatory: false
        sectionNumber: 2
      - questionType: datetimePicker
        order: 6
        question: When were you born?
        minDatetime: 1993-06-21T00:00:00  # format: %Y-%m-%dT%H:%M:%S
        maxDatetime: 2023-06-21T23:59:59  # format: %Y-%m-%dT%H:%M:%S
        mandatory: false
        sectionNumber: 2
      - questionType: numberPicker
        order: 7
        question: How old are you?
        minNumber: -100
        maxNumber: 100
        mandatory: false
        sectionNumber: 2
      - questionType: pdfUpload
        order: 8
        question: Please upload your CV
        maxFileSizeInMB: 2.0  # in Mega Byte
        mandatory: false
        sectionNumber: 2
      - questionType: imageUpload
        order: 9
        question: Please upload your Profile picture
        maxFileSizeInMB: 2.0  # in Mega Byte
        mandatory: false
        sectionNumber: 2
      - questionType: dropdown
        order: 10
        question: What's your favourite animal?
        minAnswers: 1
        maxAnswers: 1
        Answers:
          - Chameleon
          - Salmon
          - Amadillo
        mandatory: false
        userInput: true
        sectionNumber: 2
      - questionType: checkBox
        order: 11
        question: Do you agree with the Terms and Conditions of ABC?
        mandatory: false
        sectionNumber: 2
      - questionType: conditional
        order: 12
        question: Do you have previous experience in XYZ?
        Answers:
          - value: "Yes"
            questions:
              - questionType: shortText
                question: Describe your experience in XYZ.
                mandatory: true
                maxTextLength: 100
              - questionType: numberPicker
                question: How many years of experience do you have in XYZ?
                minNumber: 1
                maxNumber: 30
                mandatory: false
          - value: "No"
            questions:
              - questionType: longText
                question: What are your areas of interest?
                mandatory: false
                maxTextLength: 300
              - questionType: multipleChoice
                question: Which of these fields are you interested in learning more about?
                Answers:
                  - Field 1
                  - Field 2
                  - Field 3
                mandatory: false
                minAnswers: 0
                maxAnswers: 3
                userInput: false
        mandatory: false
        sectionNumber: 2
  phase-2:
    phaseLabel: "Test Phase 2"
    startDate: 2024-01-09
    endDate: 2024-02-15
    questions:
      - questionType: shortText
        order: 1
        question: What's your name?
        maxTextLength: 20
        mandatory: true
      - questionType: longText
        order: 2
        question: What's your name and birthday?
        mandatory: true
        maxTextLength: 200
      - questionType: multipleChoice
        order: 4
        question: What's your name and birthday?
        minAnswers: 2
        maxAnswers: 2
        Answers:
          - Possible Answer 1
          - Possible Answer 2
          - Possible Answer 3
        mandatory: false
        userInput: true
      - questionType: videoUpload
        order: 3
        question: Please Upload this Video
        mandatory: false
        maxFileSizeInMB: 10.0  # in Mega Byte
